# Generated by Django 4.2.5 on 2023-09-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraccount_display_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='display_pic',
            field=models.ImageField(blank=True, default='user/user.png', null=True, upload_to='user/'),
        ),
    ]
